import type { OkaneEntry } from './types/item';
 
export const mockEntries: OkaneEntry[] = [
  // target（年度目標）- month/day/date 為 null
  {
    id: "t1",
    team_id: "team-001",
    year: 2026,
    month: null,
    day: null,
    date: null,
    type: "in",
    stage: "target",
    confidence: null,
    category: "売上高",
    amount: 10000000,
    summary: "2026年度 売上目標",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-001",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: "Joanna",
    metadata: null,
    splits: null,
  },
  {
    id: "t2",
    team_id: "team-001",
    year: 2026,
    month: null,
    day: null,
    date: null,
    type: "out",
    stage: "target",
    confidence: null,
    category: "給料手当",
    amount: 5000000,
    summary: "2026年度 人件費目標",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-001",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: "Joanna",
    metadata: null,
    splits: null,
  },
 
  // upcoming（予定）- confidence 必填
  {
    id: "u1",
    team_id: "team-001",
    year: 2026,
    month: 6,
    day: null,
    date: null,
    type: "in",
    stage: "upcoming",
    confidence: "committed",
    category: "売上高",
    amount: 800000,
    summary: "6月 売上予定",
    contact: "A株式会社",
    note: null,
    tags: null,
    member_id: "member-001",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: "Joanna",
    metadata: null,
    splits: [
      { member_id: "member-001", member_name: "Joanna", amount: 500000 },
      { member_id: "member-002", member_name: "Keiichi", amount: 300000 },
    ],
  },
  {
    id: "u2",
    team_id: "team-001",
    year: 2026,
    month: 7,
    day: null,
    date: null,
    type: "in",
    stage: "upcoming",
    confidence: "expected",
    category: "売上高",
    amount: 600000,
    summary: "7月 売上見込み",
    contact: "B株式会社",
    note: null,
    tags: null,
    member_id: "member-002",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: null,
    metadata: null,
    splits: null,
  },
  {
    id: "u3",
    team_id: "team-001",
    year: 2026,
    month: 8,
    day: null,
    date: null,
    type: "in",
    stage: "upcoming",
    confidence: "possible",
    category: "売上高",
    amount: 400000,
    summary: "8月 売上可能性",
    contact: "C株式会社",
    note: null,
    tags: null,
    member_id: "member-002",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: null,
    metadata: null,
    splits: null,
  },
 
  // realized（実績）- date 必填
  {
    id: "r1",
    team_id: "team-001",
    year: 2026,
    month: 5,
    day: 26,
    date: "2026-05-26",
    type: "in",
    stage: "realized",
    confidence: null,
    category: "売上高",
    amount: 500000,
    summary: "5月の売上",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-001",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: "Joanna",
    metadata: null,
    splits: null,
  },
  {
    id: "r2",
    team_id: "team-001",
    year: 2026,
    month: 4,
    day: 30,
    date: "2026-04-30",
    type: "out",
    stage: "realized",
    confidence: null,
    category: "経費",
    amount: 80000,
    summary: "4月の経費",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-003",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: null,
    metadata: null,
    splits: null,
  },
  {
    id: "r3",
    team_id: "team-001",
    year: 2026,
    month: 7,
    day: 1,
    date: "2026-07-01",
    type: "in",
    stage: "realized",
    confidence: null,
    category: "売上高",
    amount: 300000,
    summary: "7月の売上",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-001",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: "Joanna",
    metadata: null,
    splits: null,
  },
];