import type { OkaneEntry } from './types/item';

export const mockEntries: OkaneEntry[] = [
  {
    id: "1",
    team_id: "team-001",
    year: 2026,
    month: 5,
    day: 26,
    date: "2026-05-26",
    type: "income",
    stage: "current",
    confidence: "committed",
    category: "売上",
    amount: 500000,
    summary: "5月の売上",
    contact: "ABC株式会社",
    note: "",
    tags: "",
    member_id: "member-001",
    version: 1,
    created_at: 1748217600,
    created_by: "Joanna",
    updated_at: 1748217600,
    updated_by: "Joanna",
  },
  {
    id: "2",
    team_id: "team-001",
    year: 2026,
    month: 6,
    day: null,
    date: null,
    type: "expense",
    stage: "upcoming",
    confidence: "committed",
    category: "経費",
    amount: 120000,
    summary: "6月の経費見込み",
    contact: "XYZ株式会社",
    note: "要確認",
    tags: "",
    member_id: "member-002",
    version: 1,
    created_at: 1748217600,
    created_by: "Joanna",
    updated_at: 1748217600,
    updated_by: "Joanna",
  },

  {
    id: "3",
    team_id: "team-001",
    year: 2026,
    month: 7,
    day: 1,
    date: "2026-07-01",
    type: "income",
    stage: "upcoming",
    confidence: "committed",
    category: "売上",
    amount: 300000,
    summary: "7月の売上見込み",
    contact: "DEF株式会社",
    note: "",
    tags: "",
    member_id: "member-001",
    version: 1,
    created_at: 1748217600,
    created_by: "Joanna",
    updated_at: 1748217600,
    updated_by: "Joanna",
  },
  {
    id: "4",
    team_id: "team-001",
    year: 2026,
    month: 4,
    day: 30,
    date: "2026-04-30",
    type: "expense",
    stage: "past",
    confidence: "committed",
    category: "経費",
    amount: 80000,
    summary: "4月の経費",
    contact: "GHI株式会社",
    note: "精算済み",
    tags: "",
    member_id: "member-003",
    version: 1,
    created_at: 1748217600,
    created_by: "Joanna",
    updated_at: 1748217600,
    updated_by: "Joanna",
  },
];