import type { OkaneEntry } from './types/item';

export const mockEntries: OkaneEntry[] = [
  {
    id: "1",
    team_id: "team-001",
    year: 2026,
    month: 5,
    day: 26,
    date: "2026-05-26",
    type: "in",
    stage: "realized",
    confidence: null,
    category: "売上",
    amount: "500000",
    summary: "5月の売上",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-001",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: "Joanna",
    metadata: null,
  },
  {
    id: "2",
    team_id: "team-001",
    year: 2026,
    month: 6,
    day: null,
    date: null,
    type: "out",
    stage: "realized",
    confidence: null,
    category: "経費",
    amount: "120000",
    summary: "6月の経費見込み",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-002",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: null,
    metadata: null,
  },
  {
    id: "3",
    team_id: "team-001",
    year: 2026,
    month: 7,
    day: 1,
    date: "2026-07-01",
    type: "in",
    stage: "realized",
    confidence: null,
    category: "売上",
    amount: "300000",
    summary: "7月の売上見込み",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-001",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: "Joanna",
    metadata: null,
  },
  {
    id: "4",
    team_id: "team-001",
    year: 2026,
    month: 4,
    day: 30,
    date: "2026-04-30",
    type: "out",
    stage: "realized",
    confidence: null,
    category: "経費",
    amount: "80000",
    summary: "4月の経費",
    contact: null,
    note: null,
    tags: null,
    member_id: "member-003",
    version: 1,
    created_at: "1748217600",
    created_by: "Joanna",
    updated_at: "1748217600",
    updated_by: "Joanna",
    member_name: null,
    metadata: null,
  },
];